languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://www.treutler.cc"
canonifyurls = true
title = "Christian Blog"
author = "Christian Treutler"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."


[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Christian"
  github = "yogitea"
  twitter = "yogitea"
  email = "treutler.cc@teadrinker.de"
  description = ""
  cv = "/pages/cv"
  legalnotice = "/pages/legal-notice"
  muut = "treutler"
  linkedin = "ctreutler"
  cover = "/images/background-cover.jpg"
  logo = "/images/chr.jpg"
